spring:
  application:
    name: eurekacoffee
  config:
    import: 'configserver:'
  cloud:
    config:
     uri: 'http://localhost:8071'
management:
   endpoints:
     web:
       exposure:
         include: '*'
   info:
     env:
       enabled: true
   endpoint:
     shutdown:
       access: unrestricted
     health:
       probes:
         enabled: true